### ISSUE TITLE
Enhance UploadStatus.svelte UI design for better visual appeal and modern aesthetics

### ISSUE THREAD

**Issue by mamertofabian** [mamertofabian/bolt-to-github#49]
### Current State
The `UploadStatus.svelte` component currently uses a basic design with minimal styling. While functional, it lacks visual polish and modern design elements that would enhance the user experience and make the upload process feel more premium and engaging.

### Current Design Issues
Looking at `src/content/UploadStatus.svelte`:

1. **Basic Color Scheme**: Simple gray background (`bg-gray-800/100`) lacks visual interest
2. **Minimal Visual Hierarchy**: Limited contrast and typography styling
3. **Simple Progress Bar**: Basic colored bar without visual enhancements
4. **Limited Animations**: Only basic opacity/transform transitions
5. **Generic Shadows**: Standard shadow without depth or modern effects
6. **Basic Icons**: Simple SVG close button without visual polish
7. **Flat Design**: Lacks modern depth, gradients, or glassmorphism effects

#### 1. Modern Design System
- **Glassmorphism Effect**: Semi-transparent background with backdrop blur
- **Enhanced Color Palette**: Rich gradients and status-specific color schemes
- **Better Typography**: Improved font weights, sizes, and spacing
- **Modern Shadows**: Multi-layered shadows for depth and realism

#### 2. Enhanced Progress Bar
```css
/* Example: Animated gradient progress bar */
.progress-bar {
  background: linear-gradient(90deg, #3b82f6, #8b5cf6, #06b6d4);
  background-size: 200% 100%;
  animation: shimmer 2s infinite;
  border-radius: 6px;
  position: relative;
  overflow: hidden;
}

.progress-bar::after {
  content: '';
  position: absolute;
  top: 0;
  left: -100%;
  width: 100%;
  height: 100%;
  background: linear-gradient(90deg, transparent, rgba(255,255,255,0.3), transparent);
  animation: slide 1.5s infinite;
}
```

#### 3. Status-Specific Visual States
- **Uploading**: Pulsing blue gradient with animated progress shimmer
- **Success**: Green gradient with checkmark animation and celebration effect
- **Error**: Red gradient with subtle shake animation and warning icon
- **Idle**: Elegant fade-out with smooth transitions

#### 4. Micro-Interactions & Animations
- **Entry Animation**: Slide-in from top-right with spring physics
- **Progress Animation**: Smooth easing with anticipation curves
- **Hover States**: Enhanced button interactions with color transitions
- **Success Celebration**: Brief scale animation with particle effects (optional)
- **Loading Spinner**: Replace percentage with elegant spinner during upload

##### Icons & Illustrations
- Replace basic close button with custom icon set
- Add status-specific icons (upload, check, warning)
- Consider micro-animations for icons

##### Background & Effects
```css
/* Modern glassmorphism background */
.upload-notification {
  background: rgba(17, 24, 39, 0.8);
  backdrop-filter: blur(16px);
  border: 1px solid rgba(255, 255, 255, 0.1);
  box-shadow: 
    0 25px 50px -12px rgba(0, 0, 0, 0.5),
    0 0 0 1px rgba(255, 255, 255, 0.05),
    inset 0 1px 0 rgba(255, 255, 255, 0.1);
}
```

##### Typography & Spacing
- Improved font hierarchy with better weights
- Better line heights and letter spacing
- More generous padding and margin relationships
- Responsive typography scaling

#### 6. Accessibility Improvements
- High contrast mode support
- Reduced motion respect for accessibility
- Better focus indicators
- ARIA labels for screen readers
- Keyboard navigation enhancements

#### 7. Mobile Responsiveness
- Adaptive sizing for different screen sizes
- Touch-friendly button areas
- Optimal positioning on mobile devices
- Gesture support for dismissing

### Design Inspiration
Consider incorporating elements from:
- **Modern Dashboard UIs**: Clean, professional appearance
- **macOS/iOS Notifications**: Elegant and unobtrusive
- **Contemporary Web Apps**: Figma, Linear, Notion-style notifications
- **Gaming UIs**: Subtle particle effects and celebrations for success states

#### Color Palette Enhancement
```css
/* Status-specific color schemes */
:root {
  --upload-primary: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  --upload-success: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  --upload-error: linear-gradient(135deg, #f093fb 0%, #f5576c 100%);
  --upload-background: rgba(17, 24, 39, 0.95);
  --upload-border: rgba(255, 255, 255, 0.1);
}
```

#### Animation System
```css
/* Smooth spring-based animations */
@keyframes slideInScale {
  0% {
    transform: translateX(100%) scale(0.9);
    opacity: 0;
  }
  100% {
    transform: translateX(0) scale(1);
    opacity: 1;
  }
}

.notification-enter {
  animation: slideInScale 0.4s cubic-bezier(0.34, 1.56, 0.64, 1);
}
```

### Expected Benefits
- **Enhanced User Experience**: More engaging and polished upload feedback
- **Brand Perception**: Professional, modern appearance increases user confidence
- **Visual Feedback**: Better progress indication and status communication
- **Accessibility**: Improved support for diverse user needs
- **Mobile Experience**: Better usability across all devices
- **Developer Experience**: More maintainable and extensible styling system

### Acceptance Criteria
- [ ] Modern glassmorphism or similar contemporary design implemented
- [ ] Enhanced color palette with status-specific themes
- [ ] Smooth animations for all state transitions
- [ ] Improved progress bar with visual enhancements
- [ ] Better typography and spacing throughout
- [ ] Enhanced accessibility features
- [ ] Mobile-responsive design
- [ ] Improved micro-interactions and hover states
- [ ] Clean, maintainable CSS architecture
- [ ] Performance optimization (smooth 60fps animations)
- [ ] Cross-browser compatibility maintained
- [ ] Reduced motion preferences respected

### Files to Modify
- `src/content/UploadStatus.svelte` - Main component
- Consider extracting styles to separate CSS/SCSS files for better organization
- Update any related type definitions if needed

### Design Process
1. **Research Phase**: Analyze modern notification designs
2. **Prototyping**: Create design concepts and variations
3. **Implementation**: Develop enhanced styling system
4. **Testing**: Ensure accessibility and performance
5. **Refinement**: Polish animations and micro-interactions

This enhancement will significantly improve the perceived quality and user experience of the upload process, making it feel more professional and engaging.
